services:
  backend:
    build:
      context: ./skyegpt-backend
    ports:
      - "8000:8000"
    env_file:
      - skyegpt-backend/.env
    depends_on:
      - frontend
  frontend:
    build:
      context: ./skyegpt-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    # if we want to use .env file for frontend, uncomment the following line
    # env_file:
    #   - skyegpt-frontend/.env
volumes:
  pgdata: {}
