version: '3.8'
services:
  backend:
    build:
      context: ./skyegpt-backend
    ports:
      - "8000:8000"
    env_file:
      - skyegpt-backend/.env
    depends_on:
      - frontend
  frontend:
    build:
      context: ./skyegpt-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./skyegpt-frontend:/app
      - node_modules:/app/node_modules
volumes:
  pgdata: {}
  node_modules: {}