services:
  backend:
    build:
      context: ./skyegpt-backend
    ports:
      - "8000:8000"
    env_file:
      - skyegpt-backend/.env
    depends_on:
      - frontend
  frontend:
    build:
      context: ./skyegpt-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
volumes:
  pgdata: {}