[tool.black]
line-length = 120
target-version = ['py313']
skip-magic-trailing-comma = true

[tool.ruff]
line-length = 120
exclude = [
    ".git",
    "__pycache__",
    "build",
    "dist",
    "venv",
]

[tool.ruff.lint]
select = ["E", "F", "W", "C", "B", "D"]
ignore = ["E203", "D203", "D213"]
[tool.ruff.lint.per-file-ignores]
"apis/*.py"  = ["B008"]   # conflict with FastAPI Depends
"tests/*.py" = ["D100", "D103", "D104"] # tests are not public methods


[tool.ruff.lint.pydocstyle]
convention = "google"  # Accepts: "google", "numpy", or "pep257".
