
name: Run unit tests and deploy to Docker repo

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  run_backend_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - run: cd skyegpt-backend && pip install --no-cache-dir -r requirements.txt
    - run: pip install pytest
    - run: cd skyegpt-backend && PYTHONPATH=$(pwd) pytest

  deploy_backend_to_docker_repo:
    needs: run_backend_unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: rplesz/skyegpt-backend
          tags: v1, latest
          registry: docker.io
          directory: skyegpt-backend
          dockerfile: ./skyegpt-backend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
  run_frontend_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - run: echo "this is where frontend unit tests are supposed to be"

  deploy_frontend_to_docker_repo:
    needs: run_frontend_unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: rplesz/skyegpt-frontend
          tags: v1, latest
          registry: docker.io
          directory: skyegpt-frontend
          dockerfile: ./skyegpt-frontend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}