name: Run unit tests

on:
  push:
    branches-ignore: 
      - main
  pull_request:
    branches:
      - main 

jobs:
  run_backend_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - run: cd skyegpt-backend && pip install --no-cache-dir -r requirements.txt
    - run: pip install pytest
    - run: cd skyegpt-backend && PYTHONPATH=$(pwd) pytest tests
  
  run_frontend_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          cache: 'npm'
          cache-dependency-path: skyegpt-frontend/package-lock.json 
      - name: Install dependencies and run tests
        run: cd skyegpt-frontend && npm ci && npm run build && npm run test
       
          