name: Run unit tests and deploy to Docker repo

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  run_backend_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - run: cd skyegpt-backend && pip install --no-cache-dir -r requirements.txt
    - run: pip install pytest
    - run: cd skyegpt-backend && PYTHONPATH=$(pwd) pytest tests

  deploy_backend_to_docker_repo:
    needs: run_backend_unit_tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push multi-platform backend image
        uses: docker/build-push-action@v5
        with:
          context: ./skyegpt-backend
          file: ./skyegpt-backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            rplesz/skyegpt-backend:latest
            rplesz/skyegpt-backend:v1
  
  run_frontend_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - run: echo "this is where frontend unit tests are supposed to be"

  deploy_frontend_to_docker_repo:
    needs: run_frontend_unit_tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push multi-platform frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./skyegpt-frontend
          file: ./skyegpt-frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            rplesz/skyegpt-frontend:latest
            rplesz/skyegpt-frontend:v1
